FROM gradle:jdk11-alpine

COPY --chown=gradle:gradle . /home/gradle/src

WORKDIR /home/gradle/src

RUN gradle build --no-daemon

WORKDIR /home/gradle/src/build/libs

CMD ["java", "-jar", "ManbusBot-1.0-SNAPSHOT.JAR"]
